version: '3.8'

networks:
  mqtt-net:
    external: true


services:
  back:
  mqtt:
    image: eclipse-mosquitto
    container_name: soil-mqtt
    restart: always
    networks:
      - mqtt-net
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf